openapi : 3.0.0
info:
  title: IwillBuy Api
  description: IwillBuy - an ecommerce app to buy and sell goods
  version: 1.0.0
  contact:
    email: amansarrafnit@gmail.com
    url: "https://amansarraf.live/"

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for localhost 
    variables:
      version:
        default: v1
        enum:
          - v1
          - v2
      protocol:
        default: http
        enum:
          - http
          - https

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer


paths:
  /register:
    get:
      tags:
        - string      #helps to group the simillar resources 
      summary: returns a greet message from school
      responses:
        '200':
          description: sucess
          content:
            application/json:
              schema:
                type: string
                example: "sample"
        
        '400':
          description: Bad Request
        '500':
          description: Internal server error  
